<?php
$caminhoImagens = 'assets/img/produtos/';

$catalogo = [
    // INSERTOS (IDs 1-25)
    [
        'id' => 1,
        'slug' => '4nkt',
        'nome' => 'Inserto 4NKT',
        'categoria' => 'Inserto',
        'subcategoria' => 'Fresamento',
        'marcas' => ['OKE', 'ZCC CT'],
        'descricao_curta' => 'Inserto de alta performance para fresamento.',
        'descricao_detalhada' => 'O Inserto 4NKT é ideal para operações de fresamento de materiais ferrosos e não ferrosos, oferecendo alto desempenho e durabilidade.',
        'imagens' => ['4NKT060308R.webp', '4NKT060308TM.webp'],
        'medidas' => [
            ['codigo' => '4NKT 060308R', 'preco' => 25.00],
            ['codigo' => '4NKT 060308TM', 'preco' => 24.00],
        ],
        'destaque' => true,
        'ativo' => true,
    ],
    [
        'id' => 2,
        'slug' => 'apkt',
        'nome' => 'Inserto APKT',
        'categoria' => 'Inserto',
        'subcategoria' => 'Fresamento',
        'marcas' => ['OKE', 'ZCC CT'],
        'descricao_curta' => 'Inserto versátil para fresamento de alta precisão.',
        'descricao_detalhada' => 'O Inserto APKT é ideal para fresamento em diversas aplicações, oferecendo ótimo controle de cavacos, acabamento superior e longa vida útil. Indicado para materiais como aço, ferro fundido e ligas leves.',
        'imagens' => ['APKT1035-OP1315.webp', 'APKT100308-APF.webp'],
        'medidas' => [
            ['codigo' => 'APKT 1035 OP1315', 'preco' => 17.00],
            ['codigo' => 'APKT 100308', 'preco' => 23.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 3,
        'slug' => 'rdkw',
        'nome' => 'Inserto RDKW',
        'categoria' => 'Inserto',
        'subcategoria' => 'Fresamento',
        'marcas' => ['OKE'],
        'descricao_curta' => 'Inserto robusto para operações pesadas de fresamento.',
        'descricao_detalhada' => 'O Inserto RDKW é ideal para desbastes pesados, proporcionando alta remoção de material com estabilidade e resistência. Usado em aço, aço inox e materiais de alta dureza.',
        'imagens' => ['RDKW1204-OP1315.webp'],
        'medidas' => [
            ['codigo' => 'RDKW 1204 OP1315', 'preco' => 18.00],
        ],
        'destaque' => true,
        'ativo' => true,
    ],
    [
        'id' => 4,
        'slug' => 'enmx',
        'nome' => 'Inserto ENMX',
        'categoria' => 'Inserto',
        'subcategoria' => 'Fresamento',
        'marcas' => ['ZCC CT'],
        'descricao_curta' => 'Inserto de alta precisão para operações exigentes.',
        'descricao_detalhada' => 'O Inserto ENMX oferece excelente desempenho em operações de fresamento e perfilamento. Projetado para garantir rigidez, precisão dimensional e estabilidade em cortes contínuos ou interrompidos. <br> Produto intercambiável com a linha LNMU 0303.',
        'imagens' => ['ENMX1206T3-GM.webp'],
        'medidas' => [
            ['codigo' => 'ENMX 1206T3 GM', 'preco' => 23.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 5,
        'slug' => 'tnmg',
        'nome' => 'Inserto TNMG',
        'categoria' => 'Inserto',
        'subcategoria' => 'Torneamento',
        'marcas' => ['KYOCERA', 'OKE', 'ZCC CT', 'SECO', 'SANDVIK'],
        'descricao_curta' => 'Inserto triangular para torneamento externo.',
        'descricao_detalhada' => 'O Inserto TNMG é utilizado principalmente em operações de torneamento externo. Seu formato triangular permite múltiplas arestas de corte e boa dissipação de calor, ideal para aço e inox.',
        'imagens' => ['TNMG160404-MQ.webp', 'TNMG160404R-D90-OP1315.webp', 'TNMG160404R-ZC.webp', 'tnmg160404-pf.webp', 'TNMG220408-M6.webp'],
        'medidas' => [
            ['codigo' => 'TNMG 160404', 'preco' => 25.00],
            ['codigo' => 'TNMG 160404R OP1315', 'preco' => 20.00],
            ['codigo' => 'TNMG 160404R YBG205', 'preco' => 22.00],
            ['codigo' => 'TNMG 160404-PF', 'preco' => 33.00],
            ['codigo' => 'TNMG 220408 M6', 'preco' => 46.00],
        ],
        'destaque' => true,
        'ativo' => true,
    ],
    [
        'id' => 6,
        'slug' => 'bdmt',
        'nome' => 'Inserto BDMT',
        'categoria' => 'Inserto',
        'subcategoria' => 'Fresamento',
        'marcas' => ['OKE'],
        'descricao_curta' => 'Inserto para fresamento leve e eficiente.',
        'descricao_detalhada' => 'O Inserto BDMT é utilizado em fresamento com baixa resistência ao corte, ideal para usinagem de alumínio e ligas leves. Garante excelente evacuação de cavacos e acabamento superficial.',
        'imagens' => ['BDMT11T308ER-JT.webp', 'BDMT11T316ER-JT.webp'],
        'medidas' => [
            ['codigo' => 'BDMT 11T308 OP1315', 'preco' => 20.00],
            ['codigo' => 'BDMT 11T316 OP1215', 'preco' => 20.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 7,
        'slug' => 'wnmg',
        'nome' => 'Inserto WNMG',
        'categoria' => 'Inserto',
        'subcategoria' => 'Torneamento',
        'marcas' => ['ZCC CT', 'OKE', 'KENNAMETAL'],
        'descricao_curta' => 'Inserto com seis arestas de corte para torneamento.',
        'descricao_detalhada' => 'O Inserto WNMG possui geometria romboide com seis arestas de corte, sendo ideal para desbaste e acabamento em aço, ferro fundido e ligas. É conhecido pela economia e versatilidade.',
        'imagens' => ['WNMG060408-EF.webp', 'WNMG080408-OPM-OC2125.webp', 'WNMG080412MV.webp'],
        'medidas' => [
            ['codigo' => 'WNMG 060408', 'preco' => 27.00],
            ['codigo' => 'WNMG 080408 OC2125', 'preco' => 23.00],
            ['codigo' => 'WNMG 080412 MW', 'preco' => 32.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 8,
        'slug' => 'rdmw',
        'nome' => 'Inserto RDMW',
        'categoria' => 'Inserto',
        'subcategoria' => 'Fresamento',
        'marcas' => ['HADSTO'],
        'descricao_curta' => 'Inserto redondo ideal para fresamento de contornos.',
        'descricao_detalhada' => 'O Inserto RDMW possui formato arredondado que permite usinagem de perfis complexos e contornos com ótima estabilidade. Excelente escolha para aplicações com múltiplas direções de corte.',
        'imagens' => ['RDMW10T3MO-FM.webp', 'RDMW12T3MO-FM.webp', 'RDMW1204MO-FM.webp'],
        'medidas' => [
            ['codigo' => 'RDMW 10T3MO', 'preco' => 14.00],
            ['codigo' => 'RDMW 12T3MO', 'preco' => 20.00],
            ['codigo' => 'RDMW 1204MO', 'preco' => 22.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 9,
        'slug' => 'apmt',
        'nome' => 'Inserto APMT',
        'categoria' => 'Inserto',
        'subcategoria' => 'Fresamento',
        'marcas' => ['HADSTO'],
        'descricao_curta' => 'Inserto de fresamento com ótimo acabamento.',
        'descricao_detalhada' => 'O Inserto APMT é muito usado em fresadoras indexáveis. Oferece ótima estabilidade e acabamento superficial em operações de desbaste leve e acabamento em aço, ferro fundido e aço inoxidável.',
        'imagens' => ['APMT1135PDERT-FM.webp'],
        'medidas' => [
            ['codigo' => 'APMT 1135PDER', 'preco' => 19.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 10,
        'slug' => 'blmp',
        'nome' => 'Inserto BLMP',
        'categoria' => 'Inserto',
        'subcategoria' => 'Fresamento',
        'marcas' => ['CRETO'],
        'descricao_curta' => 'Inserto com geometria positiva para fresamento suave.',
        'descricao_detalhada' => 'O Inserto BLMP é indicado para fresamento com baixo esforço de corte, ideal para materiais delicados ou usinagem de paredes finas. Garante bom acabamento e excelente fixação.',
        'imagens' => ['BLMP0904R-M.webp'],
        'medidas' => [
            ['codigo' => 'BLMP 0904R GT4204', 'preco' => 30.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 11,
        'slug' => 'gcmn',
        'nome' => 'Inserto GCMN',
        'categoria' => 'Inserto',
        'subcategoria' => 'Canal',
        'marcas' => ['SUMITOMO'],
        'descricao_curta' => 'Inserto para canal interno com excelente precisão.',
        'descricao_detalhada' => 'O Inserto GCMN é ideal para operações de canal interno em torneamento. Garante estabilidade, precisão dimensional e longa vida útil mesmo em materiais exigentes como aço e ferro fundido.',
        'imagens' => ['GCMN4020-RG-AC520U.webp', 'GCMN4004-GG-AC520U.webp', 'GCMN3004-GG-AC520U.webp', 'GCMN2002-GG-AC520U.webp'],
        'medidas' => [
            ['codigo' => 'GCMN 4020 AC520U', 'preco' => 45.00],
            ['codigo' => 'GCMN 4004 AC520U', 'preco' => 45.00],
            ['codigo' => 'GCMN 3004 AC520U', 'preco' => 45.00],
            ['codigo' => 'GCMN 2002 AC520U', 'preco' => 45.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 12,
        'slug' => 'gcmr',
        'nome' => 'Inserto GCMR',
        'categoria' => 'Inserto',
        'subcategoria' => 'Canal',
        'marcas' => ['SUMITOMO'],
        'descricao_curta' => 'Inserto para canal externo de alta performance.',
        'descricao_detalhada' => 'O Inserto GCMR é voltado para canal externo, com excelente rigidez e controle de cavacos. Oferece cortes limpos e seguros, ideal para peças de precisão e acabamento uniforme.',
        'imagens' => ['GCMR2002-CG-05-AC530U.webp', 'GCMR3002-CG-05-AC530U.webp', 'GCMR4002-CG-05-AC530U.webp'],
        'medidas' => [
            ['codigo' => 'GCMR 4002 AC530U', 'preco' => 45.00],
            ['codigo' => 'GCMR 3002 AC530U', 'preco' => 45.00],
            ['codigo' => 'GCMR 2002 AC530U', 'preco' => 45.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 13,
        'slug' => 'p3200',
        'nome' => 'Inserto P3200',
        'categoria' => 'Inserto',
        'subcategoria' => 'Canal',
        'marcas' => ['TUNGTIC'],
        'descricao_curta' => 'Inserto retangular para canais com ótima fixação.',
        'descricao_detalhada' => 'O Inserto P3200 é indicado para operações de canal em torneamento. Possui excelente fixação e resistência, ideal para cortes retos e estabilidade dimensional.',
        'imagens' => ['P3200-D10.webp', 'P3200-D20.webp'],
        'medidas' => [
            ['codigo' => 'P3200 D10', 'preco' => 110.00],
            ['codigo' => 'P3200 D12', 'preco' => 140.00],
            ['codigo' => 'P3200 D16', 'preco' => 145.00],
            ['codigo' => 'P3200 D20', 'preco' => 150.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 14,
        'slug' => 'p3201',
        'nome' => 'Inserto P3201',
        'categoria' => 'Inserto',
        'subcategoria' => 'Canal',
        'marcas' => ['WALTER'],
        'descricao_curta' => 'Inserto para canais profundos e estreitos.',
        'descricao_detalhada' => 'O Inserto P3201 é projetado para cortes em canais mais estreitos e profundos. Apresenta ótima durabilidade e precisão, sendo ideal para operações contínuas.',
        'imagens' => ['P3201-D10.webp'],
        'medidas' => [
            ['codigo' => 'P3201 D10', 'preco' => 130.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 15,
        'slug' => 'zomx',
        'nome' => 'Inserto ZOMX',
        'categoria' => 'Inserto',
        'subcategoria' => 'Fresamento',
        'marcas' => ['SECO'],
        'descricao_curta' => 'Inserto com múltiplas arestas para fresamento.',
        'descricao_detalhada' => 'O Inserto ZOMX possui diversas arestas de corte que otimizam o custo por aresta. Ideal para fresamento em aço e ferro fundido, com ótima remoção de cavacos.',
        'imagens' => ['ZOMX1607-16TR.webp'],
        'medidas' => [
            ['codigo' => 'ZOMX 1607 16TR', 'preco' => 85.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 16,
        'slug' => 'cnmg',
        'nome' => 'Inserto CNMG',
        'categoria' => 'Inserto',
        'subcategoria' => 'Torneamento',
        'marcas' => ['SECO'],
        'descricao_curta' => 'Inserto romboide para desbaste e acabamento.',
        'descricao_detalhada' => 'O Inserto CNMG é utilizado em torneamento de desbaste e acabamento. Com geometria versátil, oferece ótima estabilidade, múltiplas arestas e boa dissipação térmica.',
        'imagens' => ['CNMG190616-M6.webp'],
        'medidas' => [
            ['codigo' => 'CNMG 190616 M6', 'preco' => 75.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 17,
        'slug' => 'vbmt',
        'nome' => 'Inserto VBMT',
        'categoria' => 'Inserto',
        'subcategoria' => 'Torneamento',
        'marcas' => ['OKE'],
        'descricao_curta' => 'Inserto afilado para torneamento de precisão.',
        'descricao_detalhada' => 'O Inserto VBMT tem formato afilado, ideal para acabamentos finos e torneamento de contornos. Excelente para aço e aço inoxidável com alta precisão.',
        'imagens' => ['VBMT160404-OTM.webp'],
        'medidas' => [
            ['codigo' => 'VBMT 160404 OC2115', 'preco' => 23.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 18,
        'slug' => 'gy2m',
        'nome' => 'Inserto GY2M',
        'categoria' => 'Inserto',
        'subcategoria' => 'Canal',
        'marcas' => ['MITSUBISHI'],
        'descricao_curta' => 'Inserto especial para canal e corte profundo.',
        'descricao_detalhada' => 'O Inserto GY2M0250E020N é ideal para canais e cortes em profundidade. Projetado para estabilidade e ótima evacuação de cavacos em torneamento.',
        'imagens' => ['GY2M0250E020N.webp'],
        'medidas' => [
            ['codigo' => 'GY2M0250E020N', 'preco' => 52.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 19,
        'slug' => 'vnmg',
        'nome' => 'Inserto VNMG',
        'categoria' => 'Inserto',
        'subcategoria' => 'Torneamento',
        'marcas' => ['ZCC CT', 'TUNGALOY'],
        'descricao_curta' => 'Inserto afilado em V para acabamento delicado.',
        'descricao_detalhada' => 'O Inserto VNMG é usado para acabamentos com grande detalhe. Sua geometria em V permite alcançar ângulos fechados e contornos difíceis com excelente acabamento.',
        'imagens' => ['VNMG160404-EM.webp', 'VNMG160404-HRF.webp'],
        'medidas' => [
            ['codigo' => 'VNMG 160404 EM', 'preco' => 39.00],
            ['codigo' => 'VNMG 160404 HRF', 'preco' => 46.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 20,
        'slug' => 'onhu',
        'nome' => 'Inserto ONHU',
        'categoria' => 'Inserto',
        'subcategoria' => 'Fresamento',
        'marcas' => ['ZCC CT'],
        'descricao_curta' => 'Inserto redondo para fresamento de perfil.',
        'descricao_detalhada' => 'O Inserto ONHU possui geometria circular, ideal para usinagem suave em contornos variados. Proporciona alta estabilidade e vida útil prolongada.',
        'imagens' => ['ONHU08T508.webp'],
        'medidas' => [
            ['codigo' => 'ONHU 08T508', 'preco' => 65.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 21,
        'slug' => 'lnmu',
        'nome' => 'Inserto LNMU',
        'categoria' => 'Inserto',
        'subcategoria' => 'Fresamento',
        'marcas' => ['OKE'],
        'descricao_curta' => 'Inserto com alta estabilidade para fresamento pesado.',
        'descricao_detalhada' => 'O Inserto LNMU é ideal para fresamento pesado, com fixação forte e múltiplas arestas. Indicado para aço e ferro fundido em operações de remoção agressiva.',
        'imagens' => ['LNMU0303ZER.webp'],
        'medidas' => [
            ['codigo' => 'LNMU 0303ZER', 'preco' => 19.00],
        ],
        'destaque' => true,
        'ativo' => true,
    ],
    [
        'id' => 22,
        'slug' => 'hnpj',
        'nome' => 'Inserto HNPJ',
        'categoria' => 'Inserto',
        'subcategoria' => 'Torneamento',
        'marcas' => ['Generico'],
        'descricao_curta' => 'Inserto HNPJ para usinagem de precisão.',
        'descricao_detalhada' => 'O Inserto HNPJ é ideal para operações de torneamento com estabilidade e excelente acabamento superficial. Fabricado em metal duro com cobertura PVD, proporciona maior vida útil e segurança no processo.',
        'imagens' => ['HNPJ0604.webp', 'HNPJ0905.webp'],
        'medidas' => [
            ['codigo' => 'HNPJ0604', 'preco' => 55.00],
            ['codigo' => 'HNPJ0905', 'preco' => 65.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 23,
        'slug' => 'dnmg',
        'nome' => 'Inserto DNMG',
        'categoria' => 'Inserto',
        'subcategoria' => 'Torneamento',
        'marcas' => ['Generico'],
        'descricao_curta' => 'Inserto DNMG versátil para desbaste e acabamento.',
        'descricao_detalhada' => 'O Inserto DNMG é ideal para operações de torneamento contínuas e intermitentes. Com formato rombóide de 55°, oferece excelente desempenho em aço e ferro fundido. Produzido em metal duro com revestimento CVD.',
        'imagens' => ['dnmg150608-mf.webp', 'dnmg150608-pm.webp'],
        'medidas' => [
            ['codigo' => 'DNMG 150608-PM', 'preco' => 420.00],
            ['codigo' => 'DNMG 150608-MF', 'preco' => 420.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 24,
        'slug' => 'dnmx',
        'nome' => 'Inserto DNMX',
        'categoria' => 'Inserto',
        'subcategoria' => 'Torneamento',
        'marcas' => ['Generico'],
        'descricao_curta' => 'Inserto DNMX para torneamento pesado com maior rigidez.',
        'descricao_detalhada' => 'O Inserto DNMX é indicado para operações robustas com altos avanços. Possui design reforçado com canal de quebra de cavacos eficiente e excelente tenacidade. Revestimento PVD resistente ao desgaste.',
        'imagens' => ['dnmx150604-wf.webp'],
        'medidas' => [
            ['codigo' => 'DNMX 150604', 'preco' => 420.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 25,
        'slug' => 'xomx',
        'nome' => 'Inserto XOMX',
        'categoria' => 'Inserto',
        'subcategoria' => 'Fresamento',
        'marcas' => ['SECO'],
        'descricao_curta' => 'Inserto da SECO para fresamento de alto desempenho.',
        'descricao_detalhada' => 'O Inserto XOMX180608 da SECO é indicado para operações de fresamento de topo e de faceamento. Possui excelente capacidade de remoção de material com baixa vibração e maior vida útil devido ao seu revestimento de alta performance. Ideal para aços, ligas inoxidáveis e materiais fundidos.',
        'imagens' => ['XOMX180608.webp'],
        'medidas' => [
            ['codigo' => 'XOMX 180608TR-M14', 'preco' => 65.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    
    // FRESAS DE METAL DURO (IDs 100-107)
    [
        'id' => 100,
        'slug' => 'fresa-d2',
        'nome' => 'Fresa de Metal Duro D2',
        'categoria' => 'Fresa',
        'subcategoria' => 'Furação',
        'marcas' => ['Generico'],
        'descricao_curta' => 'Fresa de metal duro para micro furação com alta precisão.',
        'descricao_detalhada' => 'A Fresa D2 é ideal para usinagem de pequenos furos com alta resistência ao desgaste. Com potência de 55HRC e refrigeração interna.',
        'imagens' => ['md-d20x60x125.webp', 'md-d20x100x170.webp'],
        'medidas' => [
            ['codigo' => 'D2 20XD', 'preco' => 190.00],
            ['codigo' => 'D2,10 10XD', 'preco' => 190.00],
        ],
        'destaque' => true,
        'ativo' => true,
    ],
    [
        'id' => 101,
        'slug' => 'fresa-d3',
        'nome' => 'Fresa de Metal Duro D3',
        'categoria' => 'Fresa',
        'subcategoria' => 'Furação',
        'marcas' => ['Generico'],
        'descricao_curta' => 'Fresa de metal duro para furação de precisão em pequenas peças.',
        'descricao_detalhada' => 'A Fresa D3 possui geometria otimizada para estabilidade em furos pequenos. Com potência de 55HRC e refrigeração interna.',
        'imagens' => ['md-d20x60x125.webp', 'md-d20x100x170.webp'],
        'medidas' => [
            ['codigo' => 'D3 X 8 X 60', 'preco' => 160.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 102,
        'slug' => 'fresa-d4',
        'nome' => 'Fresa de Metal Duro D4',
        'categoria' => 'Fresa',
        'subcategoria' => 'Furação',
        'marcas' => ['Generico'],
        'descricao_curta' => 'Fresa de metal duro para aplicações gerais de usinagem.',
        'descricao_detalhada' => 'A Fresa D4 é adequada para diversos materiais, garantindo durabilidade e acabamento superior. Com potência de 55HRC e refrigeração interna.',
        'imagens' => ['md-d20x60x125.webp', 'md-d20x100x170.webp'],
        'medidas' => [
            ['codigo' => 'D4 X 10 X 75', 'preco' => 170.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 103,
        'slug' => 'fresa-d5',
        'nome' => 'Fresa de Metal Duro D5',
        'categoria' => 'Fresa',
        'subcategoria' => 'Furação',
        'marcas' => ['Generico'],
        'descricao_curta' => 'Fresa de metal duro para usinagem com desempenho estável.',
        'descricao_detalhada' => 'A Fresa D5 oferece excelente precisão dimensional em furos médios. Com potência de 55HRC e refrigeração interna.',
        'imagens' => ['md-d20x60x125.webp', 'md-d20x100x170.webp'],
        'medidas' => [
            ['codigo' => 'D5 X 12 X 85', 'preco' => 180.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 104,
        'slug' => 'fresa-d6',
        'nome' => 'Fresa de Metal Duro D6',
        'categoria' => 'Fresa',
        'subcategoria' => 'Furação',
        'marcas' => ['Generico'],
        'descricao_curta' => 'Fresa de metal duro para operações versáteis de furação.',
        'descricao_detalhada' => 'A Fresa D6 é projetada para alta produtividade e longa vida útil em materiais resistentes. Com potência de 55HRC e refrigeração interna.',
        'imagens' => ['md-d20x60x125.webp', 'md-d20x100x170.webp'],
        'medidas' => [
            ['codigo' => 'D6 X 18 x 100', 'preco' => 190.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 105,
        'slug' => 'fresa-d16',
        'nome' => 'Fresa de Metal Duro D16',
        'categoria' => 'Fresa',
        'subcategoria' => 'Furação',
        'marcas' => ['Generico'],
        'descricao_curta' => 'Fresa de metal duro para furação precisa em materiais resistentes.',
        'descricao_detalhada' => 'A Fresa possui alta durabilidade e desempenho em operações contínuas com geometria otimizada para precisão. Com potência de 55HRC e com refrigeração interna.',
        'imagens' => ['md-d16x50x115.webp', 'md-d16x80x150.webp'],
        'medidas' => [
            ['codigo' => 'D16 X 50 X 115', 'preco' => 500.00],
            ['codigo' => 'D16 X 80 X 150', 'preco' => 650.00],
        ],
        'destaque' => true,
        'ativo' => true,
    ],
    [
        'id' => 106,
        'slug' => 'fresa-d20',
        'nome' => 'Fresa de Metal Duro D20',
        'categoria' => 'Fresa',
        'subcategoria' => 'Furação',
        'marcas' => ['Generico'],
        'descricao_curta' => 'Fresa de metal duro para alto desempenho em usinagem.',
        'descricao_detalhada' => 'A Fresa oferece excelente rigidez e acabamento em processos de furação profunda. Com potência de 55HRC e com refrigeração interna.',
        'imagens' => ['md-d20x60x125.webp', 'md-d20x100x170.webp'],
        'medidas' => [
            ['codigo' => 'D20 X 60 X 125', 'preco' => 650.00],
            ['codigo' => 'D20 X 100 X 170', 'preco' => 700.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 107,
        'slug' => 'fresa-d25',
        'nome' => 'Fresa de Metal Duro D25',
        'categoria' => 'Fresa',
        'subcategoria' => 'Furação',
        'marcas' => ['Generico'],
        'descricao_curta' => 'Fresa robusta para furação em grandes diâmetros.',
        'descricao_detalhada' => 'A Fresa é voltada para aplicações industriais pesadas, garantindo precisão e vida útil prolongada mesmo em operações de alta carga. Com potência de 55HRC e com refrigeração interna.',
        'imagens' => ['md-d25x110x196.webp'],
        'medidas' => [
            ['codigo' => 'D25 X 110 X 196', 'preco' => 950.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],

    // BROCAS TMAX (IDs 200-207)
    [
        'id' => 200,
        'slug' => 'broca-tmax-d18',
        'nome' => 'Broca SECO T-Max D18',
        'categoria' => 'Broca T-Max',
        'subcategoria' => 'Furação',
        'marcas' => ['SECO'],
        'descricao_curta' => 'Broca T-Max de metal duro para furação de alta precisão.',
        'descricao_detalhada' => 'A Broca SECO T-Max D18 4XD é projetada para alto desempenho em materiais resistentes, oferecendo excelente rigidez e durabilidade. Possui refrigeração interna e geometria otimizada para máxima eficiência na usinagem.',
        'imagens' => ['brocatmax1.webp', 'brocatmax2.webp', 'brocatmax3.webp', 'brocatmax4.webp'],
        'medidas' => [
            ['codigo' => 'D18 4XD', 'preco' => 750.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 201,
        'slug' => 'broca-tmax-d19',
        'nome' => 'Broca SECO T-Max D19',
        'categoria' => 'Broca T-Max',
        'subcategoria' => 'Furação',
        'marcas' => ['SECO'],
        'descricao_curta' => 'Broca T-Max de metal duro para furação precisa em diversos materiais.',
        'descricao_detalhada' => 'A Broca SECO T-Max D19 4XD é ideal para operações contínuas e de alta exigência, garantindo furação limpa e vida útil prolongada. Conta com refrigeração interna e excelente evacuação de cavacos.',
        'imagens' => ['brocatmax1.webp', 'brocatmax2.webp', 'brocatmax3.webp', 'brocatmax4.webp'],
        'medidas' => [
            ['codigo' => 'D19 4XD', 'preco' => 750.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 202,
        'slug' => 'broca-tmax-d22',
        'nome' => 'Broca SECO T-Max D22',
        'categoria' => 'Broca T-Max',
        'subcategoria' => 'Furação',
        'marcas' => ['SECO'],
        'descricao_curta' => 'Broca T-Max de alto desempenho para usinagem precisa.',
        'descricao_detalhada' => 'A Broca SECO T-Max D22 4XD oferece máxima estabilidade e desempenho consistente, mesmo em materiais de alta dureza. Equipada com refrigeração interna e ponta de corte de alto rendimento.',
        'imagens' => ['brocatmax1.webp', 'brocatmax2.webp', 'brocatmax3.webp', 'brocatmax4.webp'],
        'medidas' => [
            ['codigo' => 'D22 4XD', 'preco' => 850.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 203,
        'slug' => 'broca-tmax-d23',
        'nome' => 'Broca SECO T-Max D23',
        'categoria' => 'Broca T-Max',
        'subcategoria' => 'Furação',
        'marcas' => ['SECO'],
        'descricao_curta' => 'Broca T-Max de metal duro para furação produtiva e estável.',
        'descricao_detalhada' => 'A Broca SECO T-Max D23 4XD garante alta eficiência e precisão em operações de furação profunda. Desenvolvida para resistir ao desgaste e reduzir paradas de máquina.',
        'imagens' => ['brocatmax1.webp', 'brocatmax2.webp', 'brocatmax3.webp', 'brocatmax4.webp'],
        'medidas' => [
            ['codigo' => 'D23 4XD', 'preco' => 850.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 204,
        'slug' => 'broca-tmax-d28',
        'nome' => 'Broca SECO T-Max D28',
        'categoria' => 'Broca T-Max',
        'subcategoria' => 'Furação',
        'marcas' => ['SECO'],
        'descricao_curta' => 'Broca T-Max para furação em alto desempenho.',
        'descricao_detalhada' => 'A Broca SECO T-Max D28 4XD é ideal para operações que exigem alto avanço e estabilidade. Oferece furação precisa e longa vida útil, com refrigeração interna.',
        'imagens' => ['brocatmax1.webp', 'brocatmax2.webp', 'brocatmax3.webp', 'brocatmax4.webp'],
        'medidas' => [
            ['codigo' => 'D28 4XD', 'preco' => 950.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 205,
        'slug' => 'broca-tmax-d29',
        'nome' => 'Broca SECO T-Max D29',
        'categoria' => 'Broca T-Max',
        'subcategoria' => 'Furação',
        'marcas' => ['SECO'],
        'descricao_curta' => 'Broca T-Max versátil com variações de profundidade de corte.',
        'descricao_detalhada' => 'A Broca SECO T-Max D29 está disponível em versões 4XD e 5XD, ideais para diferentes profundidades de furação. Oferece excelente desempenho, resistência e precisão.',
        'imagens' => ['brocatmax1.webp', 'brocatmax2.webp', 'brocatmax3.webp', 'brocatmax4.webp'],
        'medidas' => [
            ['codigo' => 'D29 4XD', 'preco' => 1000.00],
            ['codigo' => 'D29 5XD', 'preco' => 1300.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 206,
        'slug' => 'broca-tmax-d34',
        'nome' => 'Broca SECO T-Max D34',
        'categoria' => 'Broca T-Max',
        'subcategoria' => 'Furação',
        'marcas' => ['SECO'],
        'descricao_curta' => 'Broca T-Max de grande diâmetro para máxima produtividade.',
        'descricao_detalhada' => 'A Broca SECO T-Max D34 4XD oferece altíssima rigidez e desempenho em furações de grandes diâmetros. Ideal para aplicações pesadas em materiais endurecidos.',
        'imagens' => ['brocatmax1.webp', 'brocatmax2.webp', 'brocatmax3.webp', 'brocatmax4.webp'],
        'medidas' => [
            ['codigo' => 'D34 4XD', 'preco' => 1500.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
    [
        'id' => 207,
        'slug' => 'broca-tmax-d38',
        'nome' => 'Broca SECO T-Max D38',
        'categoria' => 'Broca T-Max',
        'subcategoria' => 'Furação',
        'marcas' => ['SECO'],
        'descricao_curta' => 'Broca T-Max robusta para grandes operações de furação.',
        'descricao_detalhada' => 'A Broca SECO T-Max D38 4XD é projetada para alto desempenho em operações industriais de grande escala. Oferece excelente evacuação de cavacos e acabamento superior.',
        'imagens' => ['brocatmax1.webp', 'brocatmax2.webp', 'brocatmax3.webp', 'brocatmax4.webp'],
        'medidas' => [
            ['codigo' => 'D38 4XD', 'preco' => 1800.00],
        ],
        'destaque' => false,
        'ativo' => true,
    ],
];

// Funções auxiliares
function getProdutoById(int $id): ?array {
    global $catalogo;
    foreach ($catalogo as $produto) {
        if ($produto['id'] === $id) {
            return $produto;
        }
    }
    return null;
}

function getProdutosByCategoria(string $cat): array {
    global $catalogo;
    $resultado = [];
    foreach ($catalogo as $produto) {
        if (strcasecmp($produto['categoria'], $cat) === 0 && $produto['ativo']) {
            $resultado[] = $produto;
        }
    }
    return $resultado;
}

function getProdutosDestaque(int $limite = 6): array {
    global $catalogo;
    $resultado = [];
    foreach ($catalogo as $produto) {
        if ($produto['destaque'] && $produto['ativo']) {
            $resultado[] = $produto;
            if (count($resultado) >= $limite) {
                break;
            }
        }
    }
    return $resultado;
}

function getProdutosAtivos(): array {
    global $catalogo;
    $resultado = [];
    foreach ($catalogo as $produto) {
        if ($produto['ativo']) {
            $resultado[] = $produto;
        }
    }
    return $resultado;
}

function formatarPreco(float $preco): string {
    return 'R$ ' . number_format($preco, 2, ',', '.');
}
?>
